### PR TITLE
updated openai to 1.1.1

### PR DESCRIPTION
**Pull request by gilcu3**
This PR adds the minimal necessary changes to support the new version of the `openai` python library, specifically the current version `1.1.1`. I tested all the main functionality (private chats, group chats, plugins, images, transcription, stream) and it seems to work. I had my doubts on some functions in the `utils.py` file, please check those are used as expected before merging. Most changes done were related to changes on naming and the use of the new `client` object, and followed the migration guide [here](https://github.com/openai/openai-python/discussions/631).

Having this update I hope we will be able to use the new vision and TTS models soon :)

### CODE REVIEW

**Comment by gilcu3** [comment]
Once this is merged, I can open another PR with initial support for `tts` done in [fork](https://github.com/gilcu3/chatgpt-telegram-bot/tree/tts-support)

**Comment by AlexHTW** [comment]
> Once this is merged, I can open another PR with initial support for `tts` done in [fork](https://github.com/gilcu3/chatgpt-telegram-bot/tree/tts-support)

That's awesome!
How do you feel about already submitting a PR marked as WIP so that you can get feedback already and everybody can see that this feature is in the pipeline?

**Comment by gilcu3** [comment]
> That's awesome! How do you feel about already submitting a PR marked as WIP so that you can get feedback already and everybody can see that this feature is in the pipeline?

As that branch depends on this one, I thought it would be better to wait a bit. But yeah, WIP PR sounds fine as well.

**Comment by n3d1117** [comment]
Thanks @gilcu3, I've bumped openai-python from 1.1.1 to 1.3.3 directly since there are no major changes involved

**Pull request merged**
