### PR TITLE
Add budget periods and improvements

### PR DESCRIPTION
**Pull request by AlexHTW**
I am opening this as a draft for several reasons:
1.  I only did some basic tests and have to run more tests with more variations of .env configurations. Help for testing this PR is appreciated, especially by @MBudkin and @muhammed540 for correct functionality of their requested features #106 and #150.
2. I am considering adding more improvements to this PR (see at the end), interested in more opinions on those.
3. I wanted to notify you @n3d1117 for a chance of getting this in to the next release. But I guess, it's not really that urgent. Also just interested in other peoples input at this point.

# New budget periods
- replaced the bot settings of `MONTHLY_USER_BUDGETS` and `MONTHLY_GUEST_BUDGET` with `BUDGET_PERIOD`, `USER_BUDGETS` and `GUEST_BUDGET`
  - available budget periods: `"daily"`, `"monthly"`, `"all-time"`
  - decides the time frame the given user and guest budgets are applied to
  - old env variable names are caught with a warning
  - added all-time cost tracking to usage_logs files (and initializing it with existing log data)
  - added necessary logic to budget checks and stats command 

# Improvements
- added budget logic for `"*"`- user lists
  - giving every user their own budget of the amount in the first position of `USER_BUDGETS`
- refactored budget functions for better modularization, readability and less redundancy
- improved readability of small things here and there
- added `from __future__ import annotations`, enabling Python 3.8 to handle advanced type annotations

# To do
- [x] add changes to the README
- [x] provide manual for correct budget settings. I am planning this as a thread in discussions. @n3d1117, maybe we could add it to the wiki at some point.
- [x] testing all cases and group behaviour

# Possible additions
- admin command to get specific user stats as requested [here](https://github.com/n3d1117/chatgpt-telegram-bot/pull/49#issuecomment-1493872259)
  - I think it wouldn't be too hard to add here, but actually no need to be included in this PR
- shared budgets as requested [here](https://github.com/n3d1117/chatgpt-telegram-bot/issues/106#issuecomment-1489014011)
  - I think the best way to implement it would be another bot setting for a bool `SHARED_BUDGET`
  - needs addition of collected tracking for all users or a possibly "expensive" request to read all usage_logs on every request
  - would make sense to include in this PR/same release
  - However, I am not convinced this feature is worth the effort

### CODE REVIEW

**Comment by AlexHTW** [comment]
[9cc881c](https://github.com/n3d1117/chatgpt-telegram-bot/pull/178/commits/9cc881caf0d749fcd9e3085914cc57da5a2c5d81) fixes wrong default transcription price, sorry about that.

**Comment by AlexHTW** [comment]
Finished the [Budget Manual](https://github.com/n3d1117/chatgpt-telegram-bot/discussions/184) for possible budget configurations and tested as many conditions as I could think of.

**Comment by n3d1117** [comment]
Amazing work on the PR and the budget manual @AlexHTW! 💯  I'll test it in the next days

**Comment by AlexHTW** [comment]
Thanks @n3d1117 , I will send a separate PR to fix the wrong default price of transcriptions so that it doesn't have to wait for this PR.

In other news:
Tried to remove the conflicts by merging main into this. Still the same conflict, I guess I'll have to rebase.... Maybe I shouldn't touch it anymore? 😅

**Comment by n3d1117** [comment]
Looks great @AlexHTW, merged and pinned the manual in Discussions. Could you remove `Draft` from the title? Thanks!

**Pull request merged**
