### PR TITLE
Update duckduckgo_search(fix #490)

### LINKED ISSUE #490: HTTPError with web search plugin
Any time I try to use the web plugin, I get an error like this:

```
2023-12-11 15:25:36,709 - root - INFO - Calling function web_search with arguments {"query":"best tourist destinations in England 2023","region":"uk-en"}
2023-12-11 15:25:37,108 - duckduckgo_search.duckduckgo_search - WARNING - _get_url() https://links.duckduckgo.com/d.js HTTPError 
2023-12-11 15:25:40,193 - duckduckgo_search.duckduckgo_search - WARNING - _get_url() https://links.duckduckgo.com/d.js HTTPError 
2023-12-11 15:25:43,277 - duckduckgo_search.duckduckgo_search - WARNING - _get_url() https://links.duckduckgo.com/d.js HTTPError 
2023-12-11 15:25:43,278 - root - ERROR - 
Traceback (most recent call last):
  File "/home/ben/src/n3d1117/chatgpt-telegram-bot/bot/telegram_bot.py", line 693, in prompt
    async for content, tokens in stream_response:
  File "/home/ben/src/n3d1117/chatgpt-telegram-bot/bot/openai_helper.py", line 178, in get_chat_response_stream
    response, plugins_used = await self.__handle_function_call(chat_id, response, stream=True)
  File "/home/ben/src/n3d1117/chatgpt-telegram-bot/bot/openai_helper.py", line 304, in __handle_function_call
    function_response = await self.plugin_manager.call_function(function_name, self, arguments)
  File "/home/ben/src/n3d1117/chatgpt-telegram-bot/bot/plugin_manager.py", line 59, in call_function
    return json.dumps(await plugin.execute(function_name, helper, **json.loads(arguments)), default=str)
  File "/home/ben/src/n3d1117/chatgpt-telegram-bot/bot/plugins/ddg_web_search.py", line 56, in execute
    results = list(islice(ddgs_gen, 3))
  File "/home/ben/.cache/pypoetry/virtualenvs/chatgpt-telegram-bot-lQBxQO3L-py3.10/lib/python3.10/site-packages/duckduckgo_search/duckduckgo_search.py", line 150, in text
    yield from self._text_api(keywords, region, safesearch, timelimit)
  File "/home/ben/.cache/pypoetry/virtualenvs/chatgpt-telegram-bot-lQBxQO3L-py3.10/lib/python3.10/site-packages/duckduckgo_search/duckduckgo_search.py", line 201, in _text_api
    resp = self._get_url(
  File "/home/ben/.cache/pypoetry/virtualenvs/chatgpt-telegram-bot-lQBxQO3L-py3.10/lib/python3.10/site-packages/duckduckgo_search/duckduckgo_search.py", line 89, in _get_url
    raise ex
  File "/home/ben/.cache/pypoetry/virtualenvs/chatgpt-telegram-bot-lQBxQO3L-py3.10/lib/python3.10/site-packages/duckduckgo_search/duckduckgo_search.py", line 82, in _get_url
    raise httpx._exceptions.HTTPError("")
httpx.HTTPError
```

I would just wrap it in a `try` and do some retry thing but I haven't actually gotten a ddg search to work, so I think this is not a transient failure. I'll try to look into cause further.

### PR DESCRIPTION
**Pull request by Jipok**
https://github.com/n3d1117/chatgpt-telegram-bot/issues/490

### CODE REVIEW

**Comment by CameronJGrant** [comment]
Did you test this?

**Comment by Jipok** [comment]
yes

**Comment by CameronJGrant** [comment]
The docker image doesn't build. I've fixed this issue here:
https://github.com/n3d1117/chatgpt-telegram-bot/pull/506

**Comment by k3it** [comment]
the real issue seems to be that curl_cffi does not build properly on Alpine:  https://github.com/yifeikong/curl_cffi/issues/31 and there is no wheel package.  switching to python:3.9-bookworm works, but the docker image becomes heavy.   I'm not  sure if  #506  fixes it by adding poetry or with another workarounds related to impersonate cffi build dependency (addressed outside of poetry).  curious there is a simpler way to build curl_cffi on alpine..

**Comment by CameronJGrant** [comment]
@Jipok Feel free to copy the changes from my PR to yours and I will close mine. It's the same except I add one more dependency and some small Dockerfile additions to do the fixes @k3it mentioned.

Poetry has been dropped. It's a minimal fix now:
https://github.com/n3d1117/chatgpt-telegram-bot/pull/506/commits/619421ecba7cbce0b0742f27fa63b5099fb42eff

> I'm not sure if https://github.com/n3d1117/chatgpt-telegram-bot/pull/506 fixes it by adding poetry or with another workarounds related to impersonate cffi build dependency.

The repo that hosts impersonate-cffi has a Docker image that builds it specifically for alpine. I call that image and copy over the libraries to our image to keep it light weight.

**Comment by Jipok** [comment]
https://github.com/n3d1117/chatgpt-telegram-bot/pull/506

**Comment by yifeikong** [comment]
> the real issue seems to be that curl_cffi does not build properly on Alpine: [yifeikong/curl_cffi#31](https://github.com/yifeikong/curl_cffi/issues/31) and there is no wheel package. 

`curl_cffi` maintainer here, just added Alpine support in 0.6.3b1(a beta version), which you can install explicitly by specifying the version. I hope this can resolve your issue here.

**Pull request closed without merging**
