### PR TITLE
Added the ability to define ALLOWED_TELEGRAM_GROUP_IDS for implicit permission to bot access

### PR DESCRIPTION
**Pull request by dkvdm**
Added the ability to define ALLOWED_TELEGRAM_GROUP_IDS, in order to implicitly allow users in a certain Telegram Group to be automatically permitted to interact with the telegram bot

### CODE REVIEW

**Comment by AlexHTW** [comment]
Hey @dkvdm, I think it's a good feature, however the current case is not as you described in your original issue text:

> It might be misconfiguration on my part, but I'm wondering if it's possible to allow-list an entire group chat to automatically allow the use of the bot, instead of having to add each and every user ID to the ALLOWED_TELEGRAM_USER_IDS list.

You don't have to add each user of a group to the ALLOWED_TELEGRAM_USER_IDS. If at least one member of the group is in the ALLOWED_TELEGRAM_USER_IDS every member of the group has access within the GUEST_BUDGET. See lines 631-636 and 715-724. (These parts are actually missing a check for the ADMIN_USER_IDS, which should be added soon)

Given this, I see two opposite use cases for ALLOWED_TELEGRAM_GROUP_IDS.
1. Give access to members in groups that have 0 members in ALLOWED_TELEGRAM_USER_IDS.
2. Remove access from groups that have members in ALLOWED_TELEGRAM_USER_IDS but are not in ALLOWED_TELEGRAM_GROUP_IDS.

The first case I don't see as relevant enough to warrant the addition of this feature (why would you need to add a group that has nobody you wouldn't put in allowed users?) but the second case seems useful enough - allowing admins more options and control with the group usage.

So for the second option I think the default value of ALLOWED_TELEGRAM_GROUP_IDS should be "*", keeping the current behavior of groups.
Adding group IDs to the list would remove access from all groups except the ones listed (basically the same logic as with ALLOWED_TELEGRAM_USER_IDS).
The last part to think about with this behavior is what budgets should the users of the groups be using. There I see again two options:
1. All groups make use of the one GUEST_BUDGET (shared budget among all members of all allowed groups).
2. Turn GUEST_BUDGET into a list and apply the same behavior as with user budgets. Each group ALLOWED_TELEGRAM_GROUP_IDS would have a corresponding budget in GUEST_BUDGET giving each group their own budget shared by the members.

Here I think option 1 would be enough for now and option 2 would be an upgrade at a future point (once I finished the budget rework I am currently working on 😅).

I hope I made some sense, let me know if you disagree with anything or have any questions regarding budgets.

**Comment by dkvdm** [comment]
> You don't have to add each user of a group to the ALLOWED_TELEGRAM_USER_IDS. If at least one member of the group is in the ALLOWED_TELEGRAM_USER_IDS every member of the group has access within the GUEST_BUDGET. 

I think we might actually be dealing with a bug, because the reason I submitted this PR is because this crucial part doesn't work for me: other group members aren't able to interact with the bot, even though I am a Telegram Group Admin, and I'm added to the `ALLOWED_TELEGRAM_USER_IDS`. Even though those two statements are true, none of the other members are able to interact with the bot until I add them to `ALLOWED_TELEGRAM_USER_IDS` as well. Is this simply a misconfiguration on my part? anything I'm missing here? thanks!

**Comment by dkvdm** [comment]
actually, after further testing I came to the conclusion that this feature works fine, but was broken in previous versions, which is what my experience was based on. I'll close this PR, thank you!

**Comment by AlexHTW** [comment]
@dkvdm , you are right, it is bugged, I discovered it between my message here and yours.
Currently it only works if the first user in the ALLOWED_TELEGRAM_USER_IDS is in the group, otherwise it raises an error and doesn't check further. Can you confirm this?
I am submitting a PR now

**Comment by AlexHTW** [comment]
@dkvdm could you pull the PR and test it? #149

**Comment by drbuilderpro** [comment]
sharing budget among the users is bad idea. then how restrict the bot ?? then what is the meaning of restriction??

**Pull request closed without merging**
