### PR TITLE
adding support for claude, azure, llama2, cohere

### PR DESCRIPTION
**Pull request by krrishdholakia**
Hey @noriellecruz @n3d1117, 

Noticed you're only calling OpenAI. I'm working on litellm (simple library to standardize LLM API Calls - https://github.com/BerriAI/litellm) and was wondering if we could be helpful.

Added support for Claude, Cohere, Azure and Llama2 (via Replicate) by replacing the ChatOpenAI async completion call with a litellm acompletion call. The code is pretty similar to the OpenAI class - as litellm follows the same pattern as the openai-python sdk.

Would love to know if this helps.

Happy to add additional tests / update documentation, if the initial PR looks good to you.

### CODE REVIEW

**Comment by n3d1117** [comment]
Hey @krrishdholakia, first of all congrats on your library, it looks great!
As you noticed, this project is currently focused on OpenAI only, with specific OpenAI-related features baked in such as dalle image generation, audio transcriptions using Whisper, plugins support, token usage tracker etc.

I'm afraid a lot more work would be needed to support multiple LLM providers (starting by renaming the repo 😃), but I really like the idea and I'll keep this open for future reference!

**Comment by krrishdholakia** [comment]
@n3d1117 since we map exactly to the openai sdk for completion + made the relevant changes in the PR - i'm curious what additional changes you feel might need to be made?

**Comment by n3d1117** [comment]
> i'm curious what additional changes you feel might need to be made?

off the top of my mind:
- token tracking, so that the `/stats` command can work correctly
- mapping tokens to USD costs (which right now is fixed on openai pricing), so that budgets/usage restrictions can work correctly
- handle image generation / audio transcription when not using openai (I'm unaware if other providers you mentioned offer these features)
- plugins, these too are specific to openai as far as I know, how to handle them when using a different provider?

**Comment by krrishdholakia** [comment]
hey @n3d1117 do you need / want other providers for image gen/audio transcriptions? Can get the rest of the items done pretty quickly.

**Comment by n3d1117** [comment]
Closing for inactivity

**Comment by krrishdholakia** [comment]
Hey @n3d1117 we pushed the required changes re: token usage - https://docs.litellm.ai/docs/token_usage

we also have a budget manager to enforce budget limits - https://docs.litellm.ai/docs/budget_manager

**Comment by n3d1117** [comment]
Very nice @krrishdholakia, I'll check it out

**Pull request closed without merging**
