### PR TITLE
Add balance functions to stats command

### PR DESCRIPTION
**Pull request by AlexHTW**
- added ADMIN_USER_IDS to .env, added is_admin function
- added user budget info to stats
- moved grant balance info (#75) to stats: only shown when admin and has grant balance/time left
- added OpenAI billing info for current month (ex.: https://api.openai.com/dashboard/billing/usage?start_date=2023-03-01&end_date=2023-03-31) to stats: only shown for admin
- restructured usage_text for easier personalization of output

Could probably optimize a bit by calling get_remaining_budget in is_within_budget, not sure if the redundancy is too bad right now.

### CODE REVIEW

**Comment by AlexHTW** [comment]
Probably better to explicitly list admin(s) in the .env, will test and update PR soon.

**Comment by AlexHTW** [comment]
Added ADMIN_USER_IDS to .env, user ids here have the same access as ALLOWED_TELEGRAM_USER_IDS but without budget restrictions. 
is_admin function can be used for future admin exclusive commands (like  #108).
For now only used to add the OpenAI grant and billing info to admin's stats command.

**Comment by n3d1117** [comment]
Thanks @AlexHTW, looks good!

**Comment by AlexHTW** [comment]
Thanks for the merge and the new release @n3d1117 ! 
Could you please also credit @deanxizian in the release notes for this part?

**Comment by n3d1117** [comment]
> Could you please also credit @deanxizian in the release notes for this part?

Done! Sorry, release notes were auto-generated

**Pull request merged**
