### PR TITLE
tts support (WIP)

### PR DESCRIPTION
**Pull request by gilcu3**
This PR depends on #453. It adds support for the current `tts` models from openai. Feel free to try and let me know if anything breaks.

### CODE REVIEW

**Comment by rokipet** [comment]
Hello im in window i get this error how to fix it ? 2023-11-09 11:21:27,978 - root - ERROR - ⚠️ _An error has occurred._ ⚠️
[Errno 13] Permission denied: 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\2\\tmprutw7r3l'
Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\Bot Updated\chatgpt-telegram-bot-086f8447376b3faa27631bfe13b654fd54223757\bot\openai_helper.py", line 366, in generate_speech
    response.stream_to_file(temp_file.name)
  File "C:\Program Files\Python311\Lib\site-packages\openai\_base_client.py", line 1731, in stream_to_file
    with open(file, mode="wb") as f:
         ^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\2\\tmprutw7r3l'

**Comment by gilcu3** [comment]
> Hello im in window i get this error how to fix it ? 2023-11-09 11:21:27,978 - root - ERROR - ⚠️ _An error has occurred._ ⚠️ [Errno 13] Permission denied: 'C:\Users\ADMINI~1\AppData\Local\Temp\2\tmprutw7r3l' Traceback (most recent call last): File "C:\Users\Administrator\Downloads\Bot Updated\chatgpt-telegram-bot- [086f844](https://github.com/n3d1117/chatgpt-telegram-bot/commit/086f8447376b3faa27631bfe13b654fd54223757)\bot\openai_helper.py", line 366, in generate_speech response.stream_to_file(temp_file.name) File "C:\Program Files\Python311\Lib\site-packages\openai_base_client.py", line 1731, in stream_to_file with open(file, mode="wb") as f: ^^^^^^^^^^^^^^^^^^^^^ PermissionError: [Errno 13] Permission denied: 'C:\Users\ADMINI~1\AppData\Local\Temp\2\tmprutw7r3l'
> 
> Failed to generate speech: ⚠️ An error has occurred. ⚠️ Errno 13 Permission denied: 'C:\Users\ADMINI~1\AppData\Local\Temp\2\tmprutw7r3l'

Ups, I did not know Windows would have issues with temporal files... I will change that to use files in memory, it will be more portable. Wait for my next commit on this branch.

**Comment by gilcu3** [comment]
@rokipet You can test now

**Comment by rokipet** [comment]
thanks that worked

**Comment by Gigabytedru** [comment]
I can't figure out how to use ts! is there an instruction? please

**Comment by gilcu3** [comment]
> I can't figure out how to use tts! is there an instruction? please

If you cloned this branch, you can use it with `/tts "any text to read"`

**Comment by Gigabytedru** [comment]
I have a question, can I receive responses from the GPT chat in the format of MP3 in my Telegram bot?

**Comment by gilcu3** [comment]
> I have a question, can I receive responses from the GPT chat in the format of MP3 in my Telegram bot?

It is technically possible, but not implemented yet. What's your use-case?

**Comment by kithawk** [comment]
> > I have a question, can I receive responses from the GPT chat in the format of MP3 in my Telegram bot?
> 
> It is technically possible, but not implemented yet. What's your use-case?

I can imagine a workflow when bot answers a query not with text but TTS voice message directly (so, even sending back and forth voice messages between the user and bot). Something like `REPLY_WITH_TTS=true`

**Comment by gilcu3** [comment]
> I can imagine a workflow when bot answers a query not with text but TTS voice message directly (so, even sending back and forth voice messages between the user and bot). Something like `REPLY_WITH_TTS=true`

I see your point now, I thought it was about the format of the message, which is currently a voice message, but could also be just an mp3 file. Regarding adding support for `REPLY_WITH_TTS=true` I think it could be a good idea, if you can open an issue pointing that out so that it can get implemented later once this is merge and the code stabilizes.

**Comment by n3d1117** [comment]
Thanks @gilcu3! Tested this and seems to work great, made a couple of fixes and aligned all translations. Merging now! Feel free to open a separate PR for further improvements

**Comment by Jipok** [comment]
> I can imagine a workflow when bot answers a query not with text but TTS voice message directly...

Like this https://github.com/n3d1117/chatgpt-telegram-bot/pull/468 ?

**Pull request merged**
