### PR TITLE
Add balance function

### PR DESCRIPTION
**Pull request by deanxizian**
Use `/balance` to get the balance of your OpenAI account.

IMG_2841

### CODE REVIEW

**Comment by AlexHTW** [comment]
Hey, cool idea. However I would prefer not every user to have access to this.
Balance could instead return the user specific remaining balance and only show the open AI balance to the bot admin.

Setting an admin would also enable future admin specific commands.
We could define the first user in the user list to be the admin, what do you think @n3d1117 ?

**Comment by deanxizian** [comment]
Agree！

**Comment by AlexHTW** [comment]
Hey @deanxizian,
it shows $0.000 for me. I have set usage limits in the openai account but in the credit_grants I don't see those:
'object': 'credit_summary', 'total_granted': 18.0, 'total_used': 0.0, 'total_available': 0.0, 'grants':  'grant_amount': 18.0, 'used_amount': 0.0,

What is this granted credit exactly and where can I find it in my OpenAI account?

**Comment by n3d1117** [comment]
@deanxizian cool idea! I like this, maybe more details could be shown as well? Here's what my response looks like:

```json
{
  "object": "credit_summary",
  "total_granted": 18.0,
  "total_used": 3.4544164,
  "total_available": 14.5455836,
  "grants": {
    "object": "list",
    "data": [
      {
        "object": "credit_grant",
        "id": "xxx",
        "grant_amount": 18.0,
        "used_amount": 3.4544164,
        "effective_at": 1669939200.0,
        "expires_at": 1680307200.0
      }
    ]
  }
}
```

Also, this is not in real time. The page says `data may be delayed up to 5 minutes`. Not sure if this should be included in the message too.

> What is this granted credit exactly and where can I find it in my OpenAI account? The $18.00 is also not the usage limit I set up.

@AlexHTW I believe it's the free trial usage. You can find it here: https://platform.openai.com/account/usage. I too have $18.00 of granted credit:
Screenshot 2023-03-18 at 12 01 10

**Comment by deanxizian** [comment]
Yes, it refers to the $18 free trail.
Unfortunately, this api endpoint does not appear in the official documentation. I also don't know how to find the usage limit you set up.
Here's where I find this approach: [link](https://community.openai.com/t/get-the-remaining-credits-via-the-api/18827).

**Comment by AlexHTW** [comment]
I see, thanks for the explanations!
I guess I don't see the free trial usage because I only started with the API half a year after creating my account and I read it's only available for the first 3 months.
Screenshot 2023-03-18 at 13-10-59 OpenAI API

So, in my opinion it's not that useful to the general user-base, especially in a few months, to warrant an extra command. I would suggest adding it to the /stats command and only show the admin:
- add is_admin function
```
async def is_admin(self, update: Update) -> bool:
       """
        Checks if the user is the admin of the bot.
        The first user in the user list is the admin.
        """
        if self.config['allowed_user_ids'] == '*':
            return True

        allowed_user_ids = self.config['allowed_user_ids'].split(',')

        # Check if user is the first entry of the user list
        if str(update.message.from_user.id) == allowed_user_ids[0]:
            return True

        return False
```
- add function to calculate remaining monthly budget from UsageTracker (user_budget - cost_month)
- add remaining budget value to stats text
- in stats function: if is_admin and if expires_at (in credit summary) later than today, then show remaining grant amount.
(- if we can find out how to get the remaining usage limit from open AI this could be added here aswell)

What do you think?

**Comment by n3d1117** [comment]
Sounds good to me @AlexHTW. I would just check that `len(allowed_user_ids) > 0` before accessing the first element, you never know 😃

**Comment by AlexHTW** [comment]
Awesome, I will work on it tonight and send a PR to @deanxizian fork. After he merges it would show up here, right?

**Comment by AlexHTW** [comment]
Hey @deanxizian, sorry it took so long.
I decided to do a new PR #103 for this. I included your commit, hope that's ok! Let me know what you think.

I also discovered some more unofficial endpoints, this guy has a collection: https://github.com/mc1903/PS-OpenAI/tree/main/Src/Public.

**Comment by n3d1117** [comment]
Awesome! Closing this in favor of #103

**Pull request closed without merging**
