### PR TITLE
#feat: users can delete or reset last message sent - #172

### PR DESCRIPTION
**Pull request by samdoghor**

### CODE REVIEW

**Comment by AlexHTW** [comment]
Neat feature. I guess the confused emojis are due to a missing description or is there anything wrong with the implementation @bugfloyd ?

**Comment by n3d1117** [comment]
Hi @samdoghor thanks for your contribution! I really like the idea but there are some scenarios where this is problematic.

For example, if my last message was a `/image cat` command, and the bot's last message is a photo of a cat, if I send `/unsend` command, two unrelated messages from conversation history will be removed and the cat image + command will be deleted from the chat

Will keep this open in case someone has an idea of how to handle such scenarios.

**Comment by samdoghor** [comment]
> Hi @samdoghor thanks for your contribution! I really like the idea but there are some scenarios where this is problematic.
> 
> For example, if my last message was a `/image cat` command, and the bot's last message is a photo of a cat, if I send `/unsend` command, two unrelated messages from conversation history will be removed and the cat image + command will be deleted from the chat
> 
> Will keep this open in case someone has an idea of how to handle such scenarios.

Hmmm! didn't thought of that, I was just focusing on texts. I will look into it Tomorrow.

**Comment by bugfloyd** [comment]
> Neat feature. I guess the confused emojis are due to a missing description or is there anything wrong with the implementation @bugfloyd ?

Yep, the emoji was indeed for the missing description

**Comment by steepbun** [comment]
> Hi @samdoghor thanks for your contribution! I really like the idea but there are some scenarios where this is problematic.
> 
> For example, if my last message was a `/image cat` command, and the bot's last message is a photo of a cat, if I send `/unsend` command, two unrelated messages from conversation history will be removed and the cat image + command will be deleted from the chat
> 
> Will keep this open in case someone has an idea of how to handle such scenarios.

I think this can be solved by adding the image generation (or any command really) to the bot history using a few short messages, such as "Create an image" and "Here's your image" from the user and the bot respectively.

I have done something similar in a local copy where I'm trying to implement Langchain agents and it seems to work quite well, though of course the tradeoff is giving up a few slots of memory.
That said, I have found that in practice it doesn't feel noticeable, as the image generation happens in the context of the chat anyway and it makes sense intuitively that the bot should know I generated an image.

**Comment by samdoghor** [comment]
> > Hi @samdoghor thanks for your contribution! I really like the idea but there are some scenarios where this is problematic.
> > For example, if my last message was a `/image cat` command, and the bot's last message is a photo of a cat, if I send `/unsend` command, two unrelated messages from conversation history will be removed and the cat image + command will be deleted from the chat
> > Will keep this open in case someone has an idea of how to handle such scenarios.
> 
> I think this can be solved by adding the image generation (or any command really) to the bot history using a few short messages, such as "Create an image" and "Here's your image" from the user and the bot respectively.
> 
> I have done something similar in a local copy where I'm trying to implement Langchain agents and it seems to work quite well, though of course the tradeoff is giving up a few slots of memory. That said, I have found that in practice it doesn't feel noticeable, as the image generation happens in the context of the chat anyway and it makes sense intuitively that the bot should know I generated an image.

Thank you. Haven't had time yet. Over the weekend I will work it.

**Pull request closed without merging**
