### PR TITLE
Track usage per user

### PR DESCRIPTION
**Pull request by AlexHTW**
Total tokens of each request are stored along with their date information in a JSON file per user.
A user can retrieve their current daily and monthly total token usage and the implied $-cost using the /stats command.

The feature can be used to split costs with the users (fairly) or just to inform each user of their usage. 

Looking forward to your feedback on the idea and the implementation!

The next step would be to include a way for the admin to retrieve the daily/monthly information for any user. I think it would be enough to log it (maybe at program start?). 

A further feature I am planning with this is to add the option of (daily/monthly) token usage limits per user. This would give the admin complete control of the costs, allow him to invite less trusted users and finally also sell token "credit".

Of course, for the final vision the costs of Dall-E and Whisper requests also need to be tracked.

### CODE REVIEW

**Comment by AlexHTW** [comment]
Changed PR to WIP, will add Dall-E and Whisper usage tracking later today. Releasing with only chat usage tracking would lead to compatibility issues of the user JSON files between versions.

**Comment by n3d1117** [comment]
Looking good @AlexHTW! Let me know when it's ready for review

**Comment by AlexHTW** [comment]
Hey @n3d1117 ,
I am done. I implemented usage history for chat, images and transcription.
/stats command returns usage information for current day and month.
Looking forward to your review!

**Comment by n3d1117** [comment]
This is amazing! Thanks @AlexHTW

**Comment by GuillaumeMoscou** [comment]
Great improvement! How can I, as an admin, use it to view the statistics for each user?

**Comment by AlexHTW** [comment]
Thanks @GuillaumeMoscou!
You can look inside the `/usage_log` .json files for the current $-amount spent by each user and guest user.
There are currently no commands that let the admin see stats of other users in Telegram.
Can you provide more feedback, what stats you would want to see and how you would prefer to get them? I have some ideas, but would love to hear yours first.

**Comment by GuillaumeMoscou** [comment]
> Thanks @GuillaumeMoscou! You can look inside the `/usage_log` .json files for the current $-amount spent by each user and guest user. * There are currently no commands that let the admin see stats of other users in Telegram. Can you provide more feedback, what stats you would want to see and how you would prefer to get them? I have some ideas, but would love to hear yours first.
> 
> * if you're using the docker image, [here are some suggestions](https://stackoverflow.com/a/20816397) how to have a look at files inside

Thank you very much, this fulfills my needs. 

An enhancement would be to have access to it through a command, such as /stat_users (only available for the admin chat).

As for the type of information, it would be the number of tokens for the past month and the last three days. Personally, I don't look at the cost, so that information wouldn't be useful to me.

**Comment by AlexHTW** [comment]
Happy to hear the log files are sufficient for now. 
I will definitely keep your enhancement idea in the back of my mind. There are quite a lot of other improvements I want to get to first, though.

**Pull request merged**
