### PR TITLE
Update translations.json to add `stats_vision` and `vision_fail` that was missed everywhere except English 

### PR DESCRIPTION
**Pull request by yurnov**
Issue #518 is the reason for this update. I made changes to the Ukrainian (uk) and Polish (pl) translations. Also, I reorder languages in alphabetical order by lang code, except English which is kept first.

Adding a fixes and reordering is separate commits, and reordering don't bring any changes except order.

### CODE REVIEW

**Comment by yurnov** [comment]
Hi @Rafael-6fx, would you like to review a commit  [[add missed pl messages](https://github.com/n3d1117/chatgpt-telegram-bot/pull/519/commits/daa6ecbe8de55c63634264eca96f9874bdb6c152)], tagging you as you was contributor to Polish translation.

As well, it will be nice to see come suggestions from @AlexHTW for German, from @muhammed540 for Turkish, @jvican for ES, @gkpiccoli for Brazil, @jnaskali for Finish, @Am1nCmd for Indonesian, @BjornB2 for Datch, @deanxizian for Chainese, @HoangAnhQuoc for Vietnamese, @bugfloyd for Farsi and @mirmakhamat for Uzbek translations. Guys, please don't consider my request as the spam, just as improvement suggestion, langugies that you contribution for is not consistent with English, I didn't checked all messages, but at least `stats_vision` and `vision_fail` is missed

**Comment by yurnov** [comment]
Updated subject of this PR as added all languages to close #518. Most of the languages are translated with ChatGPT with GPT-3.5 turbo model, so, it may contain some errors.

@n3d1117 as the owner/maintainer and @AlexHTW as the maintainer of translations, could you please review and accept with PR?

**Review by Rafael-6fx — APPROVED** [review]
those are absolutely perfect! Long live NLM for translation!

**Comment by n3d1117** [comment]
Thank you @yurnov and sorry for the long wait!

**Pull request merged**
