### PR TITLE
JAN-15: Little fix

### PR DESCRIPTION
**Pull request by q163i**
JAN-15: Fix README.md (docker-compose block), translations ru block. Added comments to docker files

### CODE REVIEW

**Comment by n3d1117** [comment]
Hi @q163i and thanks for your contribution! I'll be happy to merge if you could able to resolve the conflicts

**Comment by q163i** [comment]
hi @n3d1117. Done

**Comment by q163i** [comment]
What about support k8s? I can add default Helm charts for it

**Comment by q163i** [comment]
MAR-26: Add helm and update Readme.md

**Pull request closed without merging**
