### PR TITLE
Update Dockerfile so it works in Raspberry py and arm systems

### PR DESCRIPTION
**Pull request by fidel-perez**
The Dockerfile as it stands now will throw a few build errors due to the lack of pre-built files in general for the raspberry pi architecture. The proposed dockerfile works in the Raspberry pi and should work anywhere else, although it takes a bit longer to load. This is just a proposal but it could be done in a separate Dockerfile instead. Tested and working.

Ps: Thanks for this amazing work :)

### CODE REVIEW

**Comment by n3d1117** [comment]
Hi @fidel-perez and thanks for your contribution! I'm not familiar with Raspberry architecture, could you please explain the changes you made to make it work?

**Comment by TQMatvey** [comment]
i dont believe this is needed, i am running this bot on 2 ARM64 systems (rpi4b and khadas vim4) in docker, everything works flawlessly, just use `docker-compose up -d` or open an issue with specific errors and logs.

**Comment by gianlucaalfa** [comment]
Same, I don't think it is necessary.
 I'm using the bot with docker on a RPI4B and it works without flawlessy. 
 Here is my docker compose file
 
```
version: "3.7"
services:

  chatgpt4turbo:
    container_name: chatgpt4turbo
    build:
      context: "https://github.com/n3d1117/chatgpt-telegram-bot.git"
      dockerfile: ./Dockerfile
    env_file:
      - /home/pi/.config/chatbot.env
    restart: always
```

**Comment by n3d1117** [comment]
Okay, closing for now, feel free to reopen

**Pull request closed without merging**
