### PR TITLE
Added docs for OpenAI-compatibles APIs support

### PR DESCRIPTION
**Pull request by kristaller486**
The OpenAI python lib already supports changing the API_BASE, but I think it would be useful to note this in the README and .env.example

### CODE REVIEW

**Comment by n3d1117** [comment]
Thanks @kristaller486, I didn't know this. Have you tested it and does it actually work? I don't have any 3rd party APIs and I have no way of checking

**Comment by kristaller486** [comment]
Yes, I tested it with an OpenAI-compatible API for open-source LLM, such as [text-generation-webui](https://github.com/oobabooga/text-generation-webui/tree/main/extensions/openai) and [llama.cpp server api_like_OAI](https://github.com/ggerganov/llama.cpp/tree/master/examples/server). I think it will work with any other openai-compatible APIs.

**Comment by n3d1117** [comment]
Great thanks @kristaller486, lgtm!

**Comment by gilcu3** [comment]
Hi, sorry for the dumb question but where/how is exactly the new constant `OPENAI_API_BASE` used in the code? I only see it in config and docs.

**Comment by n3d1117** [comment]
Hi @gilcu3 not a dumb question at all. It's renamed to OPENAI_BASE_URL ([fixed](https://github.com/n3d1117/chatgpt-telegram-bot/commit/b8a82d868125fab10a27203abb1c4032932f6e03)) and it is used [internally](https://github.com/search?q=repo%3Aopenai%2Fopenai-python%20OPENAI_BASE_URL&type=code) in the [openai-python](https://github.com/openai/openai-python) lib :)

**Pull request merged**
