### PR TITLE
Add Indonesian translation

### PR DESCRIPTION
**Pull request by Am1nCmd**

### CODE REVIEW

**Comment by n3d1117** [comment]
Thanks @Am1nCmd! Could you please update README.md as well? Both under [features](https://github.com/n3d1117/chatgpt-telegram-bot#features) and [configuration](https://github.com/n3d1117/chatgpt-telegram-bot#additional-optional-configuration-options)

**Comment by Am1nCmd** [comment]
sure

On 14 Apr 2023, at 19.06, ned ***@***.******@***.***>> wrote:



Thanks @Am1nCmd<https://github.com/Am1nCmd>! Could you please update README.md as well? Both under features<https://github.com/n3d1117/chatgpt-telegram-bot#features> and configuration<https://github.com/n3d1117/chatgpt-telegram-bot#additional-optional-configuration-options>

**Comment by n3d1117** [comment]
@Am1nCmd please update main branch and include the following strings at the end:

```
"answer_with_chatgpt":"Answer with ChatGPT",
"ask_chatgpt":"Ask ChatGPT",
"loading":"Loading..."
```

Thanks!

**Comment by Am1nCmd** [comment]
Will do

Sent from my iPhone

On 15 Apr 2023, at 5.59 PM, ned ***@***.***> wrote:

﻿

@Am1nCmd<https://github.com/Am1nCmd> please update main branch and include the following strings at the end:

"answer_with_chatgpt":"Answer with ChatGPT",
"ask_chatgpt":"Ask ChatGPT",
"loading":"Loading..."


Thanks!

**Pull request closed without merging**
