### PR TITLE
Add support for o1 models [updated 17.12]

### PR DESCRIPTION
**Pull request by SkySlider**
https://platform.openai.com/docs/guides/reasoning

New models currently do not support system messages, function calling, streaming and other parameters, so I implemented some workarounds to integrate these models. It works if you require immediate support for these models and seems like it doesn't affect existing model functionality.

EDIT: Updated for full o1 model release

### CODE REVIEW

**Comment by lerogo** [comment]
| Traceback (most recent call last):
chatgpt-telegram-bot-1  |   File "/app/bot/openai_helper.py", line 654, in __count_tokens
chatgpt-telegram-bot-1  |     encoding = tiktoken.encoding_for_model(model)
chatgpt-telegram-bot-1  |   File "/usr/local/lib/python3.9/site-packages/tiktoken/model.py", line 103, in encoding_for_model
chatgpt-telegram-bot-1  |     return get_encoding(encoding_name_for_model(model_name))
chatgpt-telegram-bot-1  |   File "/usr/local/lib/python3.9/site-packages/tiktoken/model.py", line 90, in encoding_name_for_model
chatgpt-telegram-bot-1  |     raise KeyError(
chatgpt-telegram-bot-1  | KeyError: 'Could not automatically map o1-preview to a tokeniser. Please use `tiktoken.get_encoding` to explicitly get the tokeniser you expect.'

**Comment by lerogo** [comment]
Sorry, I got the wrong branch.

**Comment by bulat15g** [comment]
Thanks - it worked for me)

**Comment by loo-ven** [comment]
create() got an unexpected keyword argument 'maxcompletiontokens'

**Comment by SkySlider** [comment]
> create() got an unexpected keyword argument 'maxcompletiontokens'

update openai pip package, see requirenments.txt

**Comment by loo-ven** [comment]
> > create() got an unexpected keyword argument 'maxcompletiontokens'
> 
> update openai pip package, see requirenments.txt

omg thx, forgot to rebuild

**Comment by mindw00rk** [comment]
`chatgpt-telegram-bot-chatgpt-telegram-bot-1  | 2024-10-14 16:22:30,823 - telegram.ext.Application - INFO - Application started
chatgpt-telegram-bot-chatgpt-telegram-bot-1  | 2024-10-14 16:23:02,637 - root - INFO - New message received from user @a40letbezurojaya (id: 139430351)
chatgpt-telegram-bot-chatgpt-telegram-bot-1  | 2024-10-14 16:23:06,654 - root - ERROR - Exception while handling an update: ⚠️ _An error has occurred._ ⚠️
chatgpt-telegram-bot-chatgpt-telegram-bot-1  | Error code: 404 - {'error': {'message': 'The model `o1-mini` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}
chatgpt-telegram-bot-chatgpt-telegram-bot-1  | 2024-10-14 16:23:06,665 - root - ERROR - ⚠️ _An error has occurred._ ⚠️
chatgpt-telegram-bot-chatgpt-telegram-bot-1  | Error code: 404 - {'error': {'message': 'The model `o1-mini` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}
chatgpt-telegram-bot-chatgpt-telegram-bot-1  | Traceback (most recent call last):
chatgpt-telegram-bot-chatgpt-telegram-bot-1  |   File "/app/bot/openai_helper.py", line 279, in __common_get_chat_response
chatgpt-telegram-bot-chatgpt-telegram-bot-1  |     return await self.client.chat.completions.create(**common_args)
chatgpt-telegram-bot-chatgpt-telegram-bot-1  |   File "/usr/local/lib/python3.9/site-packages/openai/resources/chat/completions.py", line 1412, in create
chatgpt-telegram-bot-chatgpt-telegram-bot-1  |     return await self._post(
chatgpt-telegram-bot-chatgpt-telegram-bot-1  |   File "/usr/local/lib/python3.9/site-packages/openai/_base_client.py", line 1816, in post
chatgpt-telegram-bot-chatgpt-telegram-bot-1  |     return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
chatgpt-telegram-bot-chatgpt-telegram-bot-1  |   File "/usr/local/lib/python3.9/site-packages/openai/_base_client.py", line 1510, in request
chatgpt-telegram-bot-chatgpt-telegram-bot-1  |     return await self._request(
chatgpt-telegram-bot-chatgpt-telegram-bot-1  |   File "/usr/local/lib/python3.9/site-packages/openai/_base_client.py", line 1611, in _request
chatgpt-telegram-bot-chatgpt-telegram-bot-1  |     raise self._make_status_error_from_response(err.response) from None
chatgpt-telegram-bot-chatgpt-telegram-bot-1  | openai.NotFoundError: Error code: 404 - {'error': {'message': 'The model `o1-mini` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}
chatgpt-telegram-bot-chatgpt-telegram-bot-1  |
chatgpt-telegram-bot-chatgpt-telegram-bot-1  | The above exception was the direct cause of the following exception:
chatgpt-telegram-bot-chatgpt-telegram-bot-1  |
chatgpt-telegram-bot-chatgpt-telegram-bot-1  | Traceback (most recent call last):
chatgpt-telegram-bot-chatgpt-telegram-bot-1  |   File "/app/bot/telegram_bot.py", line 798, in prompt
chatgpt-telegram-bot-chatgpt-telegram-bot-1  |     await wrap_with_indicator(update, context, _reply, constants.ChatAction.TYPING)
chatgpt-telegram-bot-chatgpt-telegram-bot-1  |   File "/app/bot/utils.py", line 100, in wrap_with_indicator
chatgpt-telegram-bot-chatgpt-telegram-bot-1  |     await asyncio.wait_for(asyncio.shield(task), 4.5)
chatgpt-telegram-bot-chatgpt-telegram-bot-1  |   File "/usr/local/lib/python3.9/asyncio/tasks.py", line 479, in wait_for
chatgpt-telegram-bot-chatgpt-telegram-bot-1  |     return fut.result()
chatgpt-telegram-bot-chatgpt-telegram-bot-1  |   File "/usr/local/lib/python3.9/site-packages/telegram/ext/_application.py", line 1184, in __create_task_callback
chatgpt-telegram-bot-chatgpt-telegram-bot-1  |     raise exception
chatgpt-telegram-bot-chatgpt-telegram-bot-1  |   File "/usr/local/lib/python3.9/site-packages/telegram/ext/_application.py", line 1161, in __create_task_callback
chatgpt-telegram-bot-chatgpt-telegram-bot-1  |     return await coroutine  # type: ignore[misc]
chatgpt-telegram-bot-chatgpt-telegram-bot-1  |   File "/app/bot/telegram_bot.py", line 770, in _reply
chatgpt-telegram-bot-chatgpt-telegram-bot-1  |     response, total_tokens = await self.openai.get_chat_response(chat_id=chat_id, query=prompt)
chatgpt-telegram-bot-chatgpt-telegram-bot-1  |   File "/app/bot/openai_helper.py", line 142, in get_chat_response
chatgpt-telegram-bot-chatgpt-telegram-bot-1  |     response = await self.__common_get_chat_response(chat_id, query)
chatgpt-telegram-bot-chatgpt-telegram-bot-1  |   File "/usr/local/lib/python3.9/site-packages/tenacity/_asyncio.py", line 142, in async_wrapped
chatgpt-telegram-bot-chatgpt-telegram-bot-1  |     return await fn(*args, **kwargs)
chatgpt-telegram-bot-chatgpt-telegram-bot-1  |   File "/usr/local/lib/python3.9/site-packages/tenacity/_asyncio.py", line 58, in __call__
chatgpt-telegram-bot-chatgpt-telegram-bot-1  |     do = await self.iter(retry_state=retry_state)
chatgpt-telegram-bot-chatgpt-telegram-bot-1  |   File "/usr/local/lib/python3.9/site-packages/tenacity/_asyncio.py", line 110, in iter
chatgpt-telegram-bot-chatgpt-telegram-bot-1  |     result = await action(retry_state)
chatgpt-telegram-bot-chatgpt-telegram-bot-1  |   File "/usr/local/lib/python3.9/site-packages/tenacity/_asyncio.py", line 78, in inner
chatgpt-telegram-bot-chatgpt-telegram-bot-1  |     return fn(*args, **kwargs)
chatgpt-telegram-bot-chatgpt-telegram-bot-1  |   File "/usr/local/lib/python3.9/site-packages/tenacity/__init__.py", line 390, in <lambda>
chatgpt-telegram-bot-chatgpt-telegram-bot-1  |     self._add_action_func(lambda rs: rs.outcome.result())
chatgpt-telegram-bot-chatgpt-telegram-bot-1  |   File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 439, in result
chatgpt-telegram-bot-chatgpt-telegram-bot-1  |     return self.__get_result()
chatgpt-telegram-bot-chatgpt-telegram-bot-1  |   File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
chatgpt-telegram-bot-chatgpt-telegram-bot-1  |     raise self._exception
chatgpt-telegram-bot-chatgpt-telegram-bot-1  |   File "/usr/local/lib/python3.9/site-packages/tenacity/_asyncio.py", line 61, in __call__
chatgpt-telegram-bot-chatgpt-telegram-bot-1  |     result = await fn(*args, **kwargs)
chatgpt-telegram-bot-chatgpt-telegram-bot-1  |   File "/app/bot/openai_helper.py", line 288, in __common_get_chat_response
chatgpt-telegram-bot-chatgpt-telegram-bot-1  |     raise Exception(f"⚠️ _{localized_text('error', bot_language)}._ ⚠️\n{str(e)}") from e
chatgpt-telegram-bot-chatgpt-telegram-bot-1  | Exception: ⚠️ _An error has occurred._ ⚠️
chatgpt-telegram-bot-chatgpt-telegram-bot-1  | Error code: 404 - {'error': {'message': 'The model `o1-mini` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}
`
openai==1.45.0

**Comment by prygunov** [comment]
Hi! When will be merged?

**Comment by bulat15g** [comment]
@SkySlider why did you close this request?

**Comment by SkySlider** [comment]
> @SkySlider why did you close this request?

Repository is abandoned, might fork it/rebuild it from the ground up

**Pull request closed without merging**
