### PR TITLE
added deepl plugin

### PR DESCRIPTION
**Pull request by LedyBacer**

### CODE REVIEW

**Comment by n3d1117** [comment]
Thank you @LedyBacer, this looks great! Is there any chance it could work with plain http requests, so we can avoid adding a new dependency?

**Comment by LedyBacer** [comment]
> Thank you @LedyBacer, this looks great! Is there any chance it could work with plain http requests, so we can avoid adding a new dependency?

sure

**Comment by n3d1117** [comment]
Awesome, thanks! Will merge this soon

**Comment by LedyBacer** [comment]
Done!

**Pull request merged**
