### PR TITLE
whois plugin

### PR DESCRIPTION
**Pull request by jnaskali**
This plugin can answer questions like:

- Is the domain sweetnewdomain.com already taken?
- When was google.com created?
- What dns servers does duckduckgo.com use?
- When does my domain naskali.fi expire?

### CODE REVIEW

**Comment by n3d1117** [comment]
Hi @jnaskali awesome idea! Thanks for sharing.

Although I couldn't make it work until I changed:
```python
try:
    whois_result = whois.whois(kwargs['domain'])
    return whois_result
except whois.parser.PywhoisError as e:
    return {'result': 'No such domain found'}
except Exception as e:
    return {'error': 'An unexpected error occurred: ' + str(e)}
```

to:
```python
try:
    whois_result = whois.query(kwargs['domain'])
    if whois_result is None:
        return {'result': 'No such domain found'}
    return whois_result.__dict__
except Exception as e:
    return {'error': 'An unexpected error occurred: ' + str(e)}
```

Since my installation of whois had no `whois` function, only `query`. Have you seen this?

**Comment by jnaskali** [comment]
Oops... I was apparently using the python-whois package for development, which uses older syntax. Your code works with the updated whois library version I manually entered in the readme, and is more elegant.

**Comment by n3d1117** [comment]
Cool! If you update the plugin code I'll merge this asap!

**Comment by jnaskali** [comment]
Done :+1:

**Pull request merged**
