### PR TITLE
Fixing the path to the tranlsations.json

### PR DESCRIPTION
**Pull request by bestmgmt**
the translations.json is located inside the parent directory so this change will fix it.

### CODE REVIEW

**Comment by AlexHTW** [comment]
How are you starting the bot that is not working with the current version?

**Comment by AlexHTW** [comment]
Hey, @bestmgmt. Thanks! Hope you'de doing well, too! 

I understand. I asked because for me it works using `python3 bot/main.py` and `docker compose up` and I wasn't sure if changing the path might break it for others. But I guess using `__file__` will work for all options(?). 

What about the path usage_logs in `usage_tracker.py`. I suppose for you the folder is created inside the `bot` folder? 
Maybe that needs your logic aswell then... although that will then require all the people who have their usage_logs inside the bot folder now to manually move it to root... better not to touch it then 😂

Anyway, your solution seems good to me for the translations, maybe someone more knowledgeable on this topic can give their opinion on this. I am currently not able to test this for all situations.

**Comment by AlexHTW** [comment]
works for me using `python3 bot/main.py` and `docker compose up` 👍

**Comment by n3d1117** [comment]
Thanks @bestmgmt!

**Pull request merged**
