### PR TITLE
Feature/message streaming

### PR DESCRIPTION
**Pull request by deanxizian**
A simple implementation of message streaming.

However, it is not yet fully developed and does not support:

1. `SHOW_USAGE`
2. `/stats`
3. `N_CHOICES`
4. code streaming
5. ...

Hope you experts can take a look and help improve it. 😁

RPReplay_Final1679243885 2

### CODE REVIEW

**Comment by deanxizian** [comment]
#43

**Comment by h3lp1ngh4nd** [comment]
Awesome. Streaming works flawlessly 1 on 1 (Private Messages), but in a group it seems to lag and cut off.  Don't have time currently to check how and why, but maybe @deanxizian can look into / clarify this.

**Comment by n3d1117** [comment]
Hey @deanxizian thanks! I've started working on stream support today: #110 
I improved your PR and added support for SHOW_USAGE, /stats and code while streaming. I created a different branch but gave you credits, I hope you don't mind 😃 let me know what you think!

**Comment by deanxizian** [comment]
Thanks! Just go ahead!

**Comment by n3d1117** [comment]
Great, closing this in favor of #110

**Pull request closed without merging**
