### PR TITLE
Add Farsi (Persian) translation

### PR DESCRIPTION
**Pull request by bugfloyd**
I have used "fa" as the language code. You may see "per" or "ir" in some places, but the Iranian Farsi (Persian) language is officially identified as "fa" in ISO 639-1 language codes.

### CODE REVIEW

**Comment by AleksandrSidorov01** [comment]
Hi @bugfloyd , Can I ask you a question? What's the problem with doing it yourself? I think it is not very difficult to write such a language in a translator.

**Comment by bugfloyd** [comment]
> Hi @bugfloyd , Can I ask you a question? What's the problem with doing it yourself? I think it is not very difficult to write such a language in a translator.

I didn't get your point. What do you mean by doing it myself? I got some help from google translator to find the proper words, but refined and reviewed almost all the Farsi translations before committing.

**Comment by muhammed540** [comment]
> > Hi @bugfloyd , Can I ask you a question? What's the problem with doing it yourself? I think it is not very difficult to write such a language in a translator.
> 
> I didn't get your point. What do you mean by doing it myself? I got some help from google translator to find the proper words, but refined and reviewed almost all the Farsi translations before committing.

Doesn't know exactly how to contribute to a repository on Github

**Comment by bugfloyd** [comment]
> > > Hi @bugfloyd , Can I ask you a question? What's the problem with doing it yourself? I think it is not very difficult to write such a language in a translator.
> > 
> > 
> > I didn't get your point. What do you mean by doing it myself? I got some help from google translator to find the proper words, but refined and reviewed almost all the Farsi translations before committing.
> 
> Doesn't know exactly how to contribute to a repository on Github

If you are unfamiliar with git and code editors, you can still contribute to the translation of the bot into a new language using [this form](https://docs.google.com/forms/d/e/1FAIpQLSd6PGEZCyicuOpUamAT6_ubEFuaw2jyMR8PLgx-iyQk_9MVDA/viewform?usp=sf_link).

**Comment by n3d1117** [comment]
Thank you @bugfloyd!

**Pull request merged**
