### PR TITLE
Add support for quoting replied messages

### PR DESCRIPTION
**Pull request by stanislavlysenko0912**
This allows users to quote a message when replying to it in a group chat, making the conversation context clearer.
It makes no sense to add to personal chats, since the bot will already have context, so only for groups. If I'm wrong correct me 

Issue #156 

image

### CODE REVIEW

**Comment by n3d1117** [comment]
Nice one! Thanks @stanislavlysenko0912!

**Comment by aleexam** [comment]
Why only for group chats? Why bot unable to see replies to his own messages?

**Comment by stanislavlysenko0912** [comment]
> Why only for group chats? Why bot unable to see replies to his own messages?

Because in pm they see all history

**Comment by aleexam** [comment]
Не совсем понимаю, как это работает?
Можете плиз объяснить подробнее?

**Pull request merged**
