### PR TITLE
Added command to view and change the current model

### PR DESCRIPTION
**Pull request by viktor02**
Hi. I added a new command to switch between openai models: /model

Usage:

/model - get information about the current model and available models.

/model gpt-4 - change model to gpt-4

изображение

If something is wrong, tell me, I'll fix it.

### CODE REVIEW

**Comment by AlexHTW** [comment]
Hey,
great feature and should definitely be included. However as I understand the current implementation, any user can change the model for all users, which could lead to confusion. 
I think one of the following two options would be better.
1. Only change the model for that specific user. The model setting would need to be detached from the bot config somehow.
OR
2. Add the command only for admins. You would need to check with `is_admin` instead of `is_allowed` and find a way to only show this BotCommand to admins.

I would be very interested in solutions for either option because there are many other things that would be great to be able to set specifically for each user but also the ability to add admin commands that are hidden from regular users.

**Comment by viktor02** [comment]
I implemented the second option, but 

> find a way to only show this BotCommand to admins.

It seems impossible to me, Telegram only allows to set general commands. So, I removed the /model command from bot help menu and added a sending message for non-admin users when they will try to use it. 
Also added a fix in case the administrator tries to use a model that is not on the GPT_ALL_MODELS list

In theory, the first method would be preferable and more flexible, but then you would have to store user settings somewhere.

**Comment by n3d1117** [comment]
Very nice @viktor02, thanks. I agree this feature should be for admins only.

I was wondering if there's a nicer way to let the user select a model from the list? Maybe using [inline buttons](https://core.telegram.org/bots/2-0-intro#new-inline-keyboards)? (Never used them so I'm not sure how they work)

**Comment by AlexHTW** [comment]
> In theory, the first method would be preferable and more flexible, but then you would have to store user settings somewhere.
I agree, for now I think it's good enough to have it admin only.
> Well, apparently I was wrong - its possible to show a different commands to different users using [scopes](https://core.telegram.org/api/bots/menu)
Awesome, nice find! That would be really neat and make it straightforward to add new admin commands to control other environment settings without cluttering the menu for the users. 

If I may add another suggestion - I think any config changes should also be written to the .env file (`set_key`) so that they persist after a restart. @n3d1117 Do you agree? Is it okay to just `load_dotenv()` in the `telegram_bot.py` again?

**Comment by n3d1117** [comment]
> I think any config changes should also be written to the .env file (`set_key`) so that they persist after a restart. @n3d1117 Do you agree? Is it okay to just `load_dotenv()` in the `telegram_bot.py` again?

Yeah I agree!

**Comment by viktor02** [comment]
Well, something like this?
I'm not quite sure if this relative path is the right one to use

**Comment by dkvdm** [comment]
For this project, do we consider env vars mutable or immutable? because if this bot is deployed via Docker with a `env_file` param that defines `OPENAI_MODEL` that's different from what is defined in the chat, the config change set via chat will be overwritten on the next deployment. No firm opinion from my side, but just a heads up in terms of a potential footgun.

**Comment by n3d1117** [comment]
@viktor02 Should I close this in favor of https://github.com/n3d1117/chatgpt-telegram-bot/pull/183?

**Pull request closed without merging**
