### PR TITLE
Updated duckduckgo-search. (Fixes #490)

### LINKED ISSUE #490: HTTPError with web search plugin
Any time I try to use the web plugin, I get an error like this:

```
2023-12-11 15:25:36,709 - root - INFO - Calling function web_search with arguments {"query":"best tourist destinations in England 2023","region":"uk-en"}
2023-12-11 15:25:37,108 - duckduckgo_search.duckduckgo_search - WARNING - _get_url() https://links.duckduckgo.com/d.js HTTPError 
2023-12-11 15:25:40,193 - duckduckgo_search.duckduckgo_search - WARNING - _get_url() https://links.duckduckgo.com/d.js HTTPError 
2023-12-11 15:25:43,277 - duckduckgo_search.duckduckgo_search - WARNING - _get_url() https://links.duckduckgo.com/d.js HTTPError 
2023-12-11 15:25:43,278 - root - ERROR - 
Traceback (most recent call last):
  File "/home/ben/src/n3d1117/chatgpt-telegram-bot/bot/telegram_bot.py", line 693, in prompt
    async for content, tokens in stream_response:
  File "/home/ben/src/n3d1117/chatgpt-telegram-bot/bot/openai_helper.py", line 178, in get_chat_response_stream
    response, plugins_used = await self.__handle_function_call(chat_id, response, stream=True)
  File "/home/ben/src/n3d1117/chatgpt-telegram-bot/bot/openai_helper.py", line 304, in __handle_function_call
    function_response = await self.plugin_manager.call_function(function_name, self, arguments)
  File "/home/ben/src/n3d1117/chatgpt-telegram-bot/bot/plugin_manager.py", line 59, in call_function
    return json.dumps(await plugin.execute(function_name, helper, **json.loads(arguments)), default=str)
  File "/home/ben/src/n3d1117/chatgpt-telegram-bot/bot/plugins/ddg_web_search.py", line 56, in execute
    results = list(islice(ddgs_gen, 3))
  File "/home/ben/.cache/pypoetry/virtualenvs/chatgpt-telegram-bot-lQBxQO3L-py3.10/lib/python3.10/site-packages/duckduckgo_search/duckduckgo_search.py", line 150, in text
    yield from self._text_api(keywords, region, safesearch, timelimit)
  File "/home/ben/.cache/pypoetry/virtualenvs/chatgpt-telegram-bot-lQBxQO3L-py3.10/lib/python3.10/site-packages/duckduckgo_search/duckduckgo_search.py", line 201, in _text_api
    resp = self._get_url(
  File "/home/ben/.cache/pypoetry/virtualenvs/chatgpt-telegram-bot-lQBxQO3L-py3.10/lib/python3.10/site-packages/duckduckgo_search/duckduckgo_search.py", line 89, in _get_url
    raise ex
  File "/home/ben/.cache/pypoetry/virtualenvs/chatgpt-telegram-bot-lQBxQO3L-py3.10/lib/python3.10/site-packages/duckduckgo_search/duckduckgo_search.py", line 82, in _get_url
    raise httpx._exceptions.HTTPError("")
httpx.HTTPError
```

I would just wrap it in a `try` and do some retry thing but I haven't actually gotten a ddg search to work, so I think this is not a transient failure. I'll try to look into cause further.

### PR DESCRIPTION
**Pull request by CameronJGrant**
I've updated everything to the latest versions and added poetry as a dependency management system. Note that later versions of "duckduckgo-search" need to use "curl-cffi" and that brought about a host of new issues that needed to be dealt with. That's why there are a so many edits to the Dockerfile.

### CODE REVIEW

**Comment by Jipok** [comment]
Why remove requirements.txt?

**Comment by CameronJGrant** [comment]
It hasn't been removed. It's been replaced with the "pyproject.toml" file (Poetry https://python-poetry.org/).

It works the same except it ensures package versions work together. It also generates a lock file, with hashes for each package, so that your environment is identical to everyone elses. This is especially important when building Dockerfiles. Otherwise we can have a situation where "chatgpt-telegram-bot" works on your system, but not on mine.

If you're not familiar with it, check it out. It will help with future projects.

**Comment by Jipok** [comment]
> It hasn't been removed.

It was clearly deleted judging by what Github shows.

> It works the same except...

except that it requires installing poetry. In which I don’t see any point at all for such projects.
From my point of view, you are adding an additional dependency that needs to be installed on the system in order to have a slightly more convenient way of describing dependencies. I really don’t like this kind of stuff, it’s overcomplicated. I don't understand why you're bringing Docker into this at all.

**Comment by k3it** [comment]
@Jipok has a point.  it looks like poetry repo has 612 open issues and 85 pull requests, so it's a highly complex dependency all by itself.

**Comment by CameronJGrant** [comment]
> I don't understand why you're bringing Docker into this at all.

This project builds a docker image. If you had actually tested your changes like you said you had, you would have seen it doesn't build anymore with your PR. That's my entire reason for making a PR in the first place.

> @Jipok has a point. it looks like poetry repo has 612 open issues and 85 pull requests, so it's a highly complex dependency all by itself.

Sure, Poetry is one solution. We could use pipenv instead. It doesn't matter to me. I'm just saying it's better practice to generate a lock file of some kind than simply using a requirements.txt. If everyone really wants to stick with a requirements.txt file that's fine too.

**Comment by CameronJGrant** [comment]
I've made this simpler now. No more Poetry.

**Comment by k3it** [comment]
quick tested and the build works with the #501  (#504 also),  looks good to me.  thank you!

**Comment by k3it** [comment]
paging @n3d1117

**Comment by tobias-strenger** [comment]
For me this literally doubled the image size. Dive shows a lot of gcc related stuff in /usr/lib/. I don't know exactly how to get rid of this without killing dependencies.

**Review by A1RWALK3R — CHANGES_REQUESTED** [review]
For now it is 

duckduckgo_search~=5.0
curl-cffi~=0.6.3b1

**Comment by n3d1117** [comment]
Hi all, sorry for the long wait, are these changes still relevant? Or is it enough to update to latest `duckduckgo_search` and `curl-cffi` like @A1RWALK3R suggested?

**Comment by CameronJGrant** [comment]
Thanks to @yifeikong for his update of curl_cffi @A1RWALK3R suggestion should do it.

**Comment by chk86** [comment]
This fix no longer works. DDG is returning "Failed to get response...202 Ratelimit".

**Comment by chk86** [comment]
And by this fix I mean @A1RWALK3R 's suggestion.

**Comment by A1RWALK3R** [comment]
@chk86 I think you can try duckduckgo_search==5.3.0b4

I haven't checked it yet, but I found useful information about 202 Ratelimit [here](https://github.com/deedy5/duckduckgo_search/issues/213)

**Comment by chk86** [comment]
Thanks, @A1RWALK3R . I saw that actually, that fix doesn't work, either. I tried recreating the bot with that version. I'll just be patient till they get it sorted.

**Pull request closed without merging**
