### PR TITLE
gpt-4-turbo

### PR DESCRIPTION
**Pull request by upstream-team**

### CODE REVIEW

**Comment by Jipok** [comment]
functions support?

**Comment by upstream-team** [comment]
No, I only updated the available model

**Comment by gianlucaalfa** [comment]
> Functions support? Vision support?

The new gpt-4-turbo is great beacuse it has vision AND functions support in the same model, and it's out of beta.

@upstream-team 
https://github.com/gianlucaalfa/chatgpt-telegram-bot/commit/6e2a4852ca64f51a0bd0186803ac8b6779cd0748
Use this as an example, I tested it in my enviroment and it works great.

**Comment by NeoChen1024** [comment]
Will this be merged soon?

**Pull request merged**
